# project information
site_name: jasper note
site_author: jasper
site_description: java learn note
repo_url: https://github.com/jaspercliff/jaspercliff.github.io.git
theme:
  name: material
  favicon: /assets/img/favicon.ico
  logo: /assets/img/logo.png
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.top
  - search.suggest
  - search.highlight
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - content.code.copy #代码复制按钮
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/extra.js  
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences: # mermaid
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
# Page tree
nav:
  - Java:
      - basic: 'java/basic.md'
      - object-oriented: 'java/object-oriented.md'
      - 异常: 'java/异常.md'
      - 注解: 'java/注解.md'
      - 泛型: 'java/泛型.md'
      - 反射: 'java/反射.md'
      - 集合:
          - index: 'java/collection/index.md'
          - ArrayList: 'java/collection/ArrayList.md'
          - LinkedList: 'java/collection/LinkedList.md'
          - HashMap: 'java/collection/HashMap.md'
      - IO: 'java/IO.md'
      - 多线程: 'java/多线程.md'
      - 网络编程: 'java/网络编程.md'
      - terminology: 'java/terminology.md'
      - utils: 'java/utils.md'
  - database:
      - mysql:
          - jdbc: 'database/mysql/jdbc.md'
      - redis:
          - basic: 'database/redis/index.md'
  - 设计模式:
    - 代理模式: 'designpattern/proxy.md'
  #  - spring:
  #      - springFramework:
  #          - index: ''
  #          - 过滤器.拦截器.spring切面: ''
  #      - springboot:
  #          - index: ''


